# Generated by Django 4.2.7 on 2024-03-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='card_images', verbose_name='Изображение карточки')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='CardsBig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('image', models.ImageField(upload_to='card_big_images', verbose_name='Крупное изображение проекта')),
                ('skills', models.CharField(max_length=500, verbose_name='Скиллы')),
                ('cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cards', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Карточку',
                'verbose_name_plural': 'Карточки',
                'db_table': 'card_big',
            },
        ),
    ]
